// src/components/Button/Button.tsx
import React, { forwardRef, useEffect } from 'react';

import {
  BUTTON_CLASS_NAME,
  BUTTON_ICON_CLASS,
  BUTTON_LABEL_CLASS,
  BUTTON_LEADING_ICON_CLASS,
  BUTTON_TRAILING_ICON_CLASS,
  BUTTON_SPINNER_CLASS,
  BUTTON_CARET_CLASS,
  DEFAULT_BUTTON_SIZE,
  DEFAULT_BUTTON_VARIANT,
  type ButtonSize,
  type ButtonVariant,
  ensureButtonStyles,
} from './button.styles';
import type { ButtonColor } from './color-overrides';
import { createButtonColorOverrides } from './color-overrides';
import { Icon } from '@components/Icon';

function cx(...values: Array<string | undefined | false | null>): string {
  return values.filter(Boolean).join(' ');
}

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  /** Visual style of the button. Defaults to `primary`. */
  variant?: ButtonVariant;
  /** Preset palette identifier. Initially supports success/warning/error variants. */
  color?: ButtonColor;
  /** Compact (`sm`), default (`md`), or spacious (`lg`) sizing scale. Defaults to `md`. */
  size?: ButtonSize;
  /** When `true`, the button stretches to fill the width of its container. */
  fullWidth?: boolean;
  /** Visible label text. Prefer this over children for simple usage. */
  label?: React.ReactNode;
  /** Optional leading icon rendered before the label. */
  leadingIcon?: React.ReactNode;
  /** Convenience prop: renders the shared Icon component before the label. */
  leadingIconName?: string;
  /** Optional trailing icon rendered after the label. */
  trailingIcon?: React.ReactNode;
  /** Convenience prop: renders the shared Icon component after the label. */
  trailingIconName?: string;
  /** Overrides the surface color via a design token string (e.g., `background-primary-success`). */
  surfaceColor?: string;
  /** Overrides the border color via a design token string (e.g., `border-primary-success`). */
  borderColor?: string;
  /** Overrides the text color via a design token string (e.g., `text-on-primary`). */
  textColor?: string;
  /** Overrides the accent color used for state layers via a design token string. */
  accentColor?: string;
  /** Hides the visible label for icon-only buttons. Provide an `aria-label`. */
  iconOnly?: boolean;
  /** Overrides automatic label detection when rendering a visually hidden label. */
  hasLabel?: boolean;
  /** Adds a disclosure caret to the button. */
  dropdown?: boolean;
  /** Displays a spinner and marks the button as busy. */
  loading?: boolean;
}

function hasLabelContent(children: React.ReactNode): boolean {
  return React.Children.toArray(children).some((child) => {
    if (typeof child === 'string') {
      return child.trim().length > 0;
    }

    if (typeof child === 'number') {
      return true;
    }

    if (React.isValidElement(child)) {
      if (child.type === React.Fragment) {
        return hasLabelContent(child.props.children);
      }

      if ('children' in child.props) {
        return hasLabelContent(child.props.children);
      }

      return true;
    }

    return false;
  });
}

function capitalizeTokenSegment(segment: string): string {
  if (!segment) {
    return segment;
  }

  return segment[0].toUpperCase() + segment.slice(1);
}

function toCssVariableName(token: string): string {
  const [first, ...rest] = token.split('-');
  const suffix = rest.map(capitalizeTokenSegment).join('');
  return `--${first}${suffix}`;
}

function isDesignToken(value: string): boolean {
  return /^[a-z]+(?:-[a-z0-9]+)+$/i.test(value);
}

function resolveColorValue(value: string | undefined): string | undefined {
  if (!value) {
    return value;
  }

  if (value.startsWith('var(') || value.startsWith('calc(')) {
    return value;
  }

  if (isDesignToken(value)) {
    return `var(${toCssVariableName(value)})`;
  }

  return value;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(props, ref) {
  const {
    variant = DEFAULT_BUTTON_VARIANT,
    color,
    size = DEFAULT_BUTTON_SIZE,
    fullWidth = false,
    label,
    leadingIcon,
    leadingIconName,
    trailingIcon,
    trailingIconName,
    surfaceColor,
    borderColor,
    textColor,
    accentColor,
    iconOnly = false,
    hasLabel,
    dropdown = false,
    loading = false,
    className,
    style: styleProp,
    children,
    type,
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledBy,
    'aria-haspopup': ariaHasPopup,
    'aria-expanded': ariaExpanded,
    ...rest
  } = props;

  useEffect(() => {
    ensureButtonStyles();
  }, []);

  useEffect(() => {
    if (
      process.env.NODE_ENV !== 'production' &&
      iconOnly &&
      !ariaLabel &&
      !ariaLabelledBy
    ) {
      // eslint-disable-next-line no-console
      console.warn(
        'Button: iconOnly buttons must include an accessible name via `aria-label` or `aria-labelledby`.',
      );
    }
  }, [ariaLabel, ariaLabelledBy, iconOnly]);

  const content = children ?? label;
  const resolvedHasLabel =
    typeof hasLabel === 'boolean'
      ? hasLabel
      : iconOnly
        ? false
        : hasLabelContent(content);
  const buttonType = type ?? 'button';
  const resolvedAriaHasPopup = ariaHasPopup ?? (dropdown ? 'menu' : undefined);

  const semanticOverrides =
    color ? (createButtonColorOverrides(variant, color) as unknown as React.CSSProperties) : undefined;

  const directOverrides: React.CSSProperties | undefined =
    surfaceColor || borderColor || textColor || accentColor
      ? ({
          ...(surfaceColor
            ? { ['--fivra-button-surface' as any]: resolveColorValue(surfaceColor) }
            : {}),
          ...(borderColor
            ? { ['--fivra-button-border' as any]: resolveColorValue(borderColor) }
            : {}),
          ...(textColor
            ? { ['--fivra-button-text' as any]: resolveColorValue(textColor) }
            : {}),
          ...(accentColor
            ? { ['--fivra-button-accent' as any]: resolveColorValue(accentColor) }
            : {}),
        } satisfies React.CSSProperties)
      : undefined;

  const mergedStyle =
    semanticOverrides || directOverrides || styleProp
      ? ({
          ...(semanticOverrides ?? {}),
          ...(directOverrides ?? {}),
          ...(styleProp as React.CSSProperties | undefined),
        } satisfies React.CSSProperties)
      : undefined;

  const resolvedLeadingIcon =
    leadingIcon ?? (leadingIconName ? (
      <Icon name={leadingIconName} variant="solid" color="currentColor" aria-hidden="true" />
    ) : null);
  const resolvedTrailingIcon =
    trailingIcon ?? (trailingIconName ? (
      <Icon name={trailingIconName} variant="solid" color="currentColor" aria-hidden="true" />
    ) : null);

  return (
    <button
      {...rest}
      ref={ref}
      type={buttonType}
      style={mergedStyle}
      className={cx(
        BUTTON_CLASS_NAME,
        className ?? undefined,
      )}
      data-variant={variant}
      data-size={size}
      data-full-width={fullWidth ? 'true' : undefined}
      data-icon-only={iconOnly ? 'true' : undefined}
      data-has-label={resolvedHasLabel ? 'true' : 'false'}
      data-dropdown={dropdown ? 'true' : undefined}
      data-loading={loading ? 'true' : undefined}
      aria-label={ariaLabel}
      aria-labelledby={ariaLabelledBy}
      aria-haspopup={resolvedAriaHasPopup}
      aria-expanded={ariaExpanded}
      aria-busy={loading || undefined}
    >
      {loading ? <span className={BUTTON_SPINNER_CLASS} aria-hidden="true" /> : null}
      {resolvedLeadingIcon ? (
        <span className={cx(BUTTON_ICON_CLASS, BUTTON_LEADING_ICON_CLASS)} aria-hidden="true">
          {resolvedLeadingIcon}
        </span>
      ) : null}
      {resolvedHasLabel ? <span className={BUTTON_LABEL_CLASS}>{content}</span> : null}
      {resolvedTrailingIcon ? (
        <span className={cx(BUTTON_ICON_CLASS, BUTTON_TRAILING_ICON_CLASS)} aria-hidden="true">
          {resolvedTrailingIcon}
        </span>
      ) : null}
      {dropdown ? <span className={BUTTON_CARET_CLASS} aria-hidden="true" /> : null}
    </button>
  );
});

Button.displayName = 'Button';

export { Button };
export type { ButtonVariant, ButtonSize };

// src/web-components/button.ts
import {
  BUTTON_CLASS_NAME,
  BUTTON_ICON_CLASS,
  BUTTON_LABEL_CLASS,
  BUTTON_LEADING_ICON_CLASS,
  BUTTON_TRAILING_ICON_CLASS,
  BUTTON_SPINNER_CLASS,
  BUTTON_CARET_CLASS,
  DEFAULT_BUTTON_SIZE,
  DEFAULT_BUTTON_VARIANT,
  BUTTON_SIZES,
  BUTTON_VARIANTS,
  buttonClassStyles,
  buttonHostStyles,
} from '@components/Button/button.styles';
import type { ButtonColor, ButtonSemanticStyleOverrides } from '@components/Button/color-overrides';
import { createButtonColorOverrides } from '@components/Button/color-overrides';

type ButtonVariant = (typeof BUTTON_VARIANTS)[number];
type ButtonSize = (typeof BUTTON_SIZES)[number];

function isButtonColor(value: unknown): value is ButtonColor {
  return value === 'primary-success' || value === 'primary-warning' || value === 'primary-error';
}

const TONE_STYLE_VARS: Array<keyof ButtonSemanticStyleOverrides> = [
  '--fivra-button-surface',
  '--fivra-button-accent',
  '--fivra-button-border',
  '--fivra-button-text',
  '--fivra-button-hover-fallback',
  '--fivra-button-active-fallback',
];

type DirectStyleKey =
  | '--fivra-button-surface'
  | '--fivra-button-accent'
  | '--fivra-button-border'
  | '--fivra-button-text';

const DIRECT_STYLE_VARS: DirectStyleKey[] = [
  '--fivra-button-surface',
  '--fivra-button-accent',
  '--fivra-button-border',
  '--fivra-button-text',
];

function capitalizeTokenSegment(segment: string): string {
  if (!segment) {
    return segment;
  }

  return segment[0].toUpperCase() + segment.slice(1);
}

function toCssVariableName(token: string): string {
  const [first, ...rest] = token.split('-');
  const suffix = rest.map(capitalizeTokenSegment).join('');
  return `--${first}${suffix}`;
}

function isDesignToken(value: string): boolean {
  return /^[a-z]+(?:-[a-z0-9]+)+$/i.test(value);
}

function resolveColorValue(value: string | null): string | null {
  if (!value) {
    return null;
  }

  if (value.startsWith('var(') || value.startsWith('calc(')) {
    return value;
  }

  if (isDesignToken(value)) {
    return `var(${toCssVariableName(value)})`;
  }

  return value;
}

const template = document.createElement('template');

template.innerHTML = `
  <style>
    ${buttonHostStyles}
    ${buttonClassStyles}
  </style>
  <button
    class="${BUTTON_CLASS_NAME}"
    part="button"
    type="button"
    data-variant="${DEFAULT_BUTTON_VARIANT}"
    data-size="${DEFAULT_BUTTON_SIZE}"
    data-has-label="false"
  >
    <span class="${BUTTON_SPINNER_CLASS}" part="spinner" aria-hidden="true"></span>
    <span class="${BUTTON_ICON_CLASS} ${BUTTON_LEADING_ICON_CLASS}" part="leading-icon" data-empty="true" aria-hidden="true">
      <slot name="leading-icon"></slot>
    </span>
    <span class="${BUTTON_LABEL_CLASS}" part="label" data-empty="true">
      <span part="label-text" data-label-text></span>
      <slot></slot>
    </span>
    <span class="${BUTTON_ICON_CLASS} ${BUTTON_TRAILING_ICON_CLASS}" part="trailing-icon" data-empty="true" aria-hidden="true">
      <slot name="trailing-icon"></slot>
    </span>
    <span class="${BUTTON_CARET_CLASS}" part="caret" aria-hidden="true"></span>
  </button>
`;

export class FivraButtonElement extends HTMLElement {
  static get observedAttributes(): string[] {
    return [
      'variant',
      'color',
      'label',
      'surface-color',
      'border-color',
      'text-color',
      'accent-color',
      'size',
      'disabled',
      'full-width',
      'type',
      'icon-only',
      'dropdown',
      'loading',
      'has-label',
      'aria-label',
      'aria-labelledby',
      'aria-haspopup',
      'aria-expanded',
    ];
  }

  private readonly buttonEl: HTMLButtonElement;
  private readonly leadingWrapper: HTMLElement;
  private readonly trailingWrapper: HTMLElement;
  private readonly labelWrapper: HTMLElement;
  private readonly labelTextEl: HTMLElement;
  private readonly leadingSlot: HTMLSlotElement;
  private readonly trailingSlot: HTMLSlotElement;
  private readonly labelSlot: HTMLSlotElement;

  constructor() {
    super();
    const root = this.attachShadow({ mode: 'open' });
    root.appendChild(template.content.cloneNode(true));

    this.buttonEl = root.querySelector('button') as HTMLButtonElement;
    this.leadingWrapper = root.querySelector('[part="leading-icon"]') as HTMLElement;
    this.trailingWrapper = root.querySelector('[part="trailing-icon"]') as HTMLElement;
    this.labelWrapper = root.querySelector('[part="label"]') as HTMLElement;
    this.labelTextEl = this.labelWrapper.querySelector('[data-label-text]') as HTMLElement;
    this.leadingSlot = this.leadingWrapper.querySelector('slot') as HTMLSlotElement;
    this.trailingSlot = this.trailingWrapper.querySelector('slot') as HTMLSlotElement;
    this.labelSlot = this.labelWrapper.querySelector('slot') as HTMLSlotElement;
  }

  connectedCallback(): void {
    this.syncAll();
    this.leadingSlot.addEventListener('slotchange', this.syncSlots);
    this.trailingSlot.addEventListener('slotchange', this.syncSlots);
    this.labelSlot.addEventListener('slotchange', this.syncSlots);
  }

  disconnectedCallback(): void {
    this.leadingSlot.removeEventListener('slotchange', this.syncSlots);
    this.trailingSlot.removeEventListener('slotchange', this.syncSlots);
    this.labelSlot.removeEventListener('slotchange', this.syncSlots);
  }

  attributeChangedCallback(): void {
    this.syncAll();
  }

  focus(options?: FocusOptions): void {
    this.buttonEl.focus(options);
  }

  click(): void {
    this.buttonEl.click();
  }

  get variant(): ButtonVariant {
    return (this.buttonEl.dataset.variant as ButtonVariant) ?? DEFAULT_BUTTON_VARIANT;
  }

  set variant(value: ButtonVariant) {
    this.setAttribute('variant', value);
  }

  get color(): ButtonColor | null {
    const attr = this.getAttribute('color');
    return isButtonColor(attr) ? (attr as ButtonColor) : null;
  }

  set color(value: ButtonColor | null) {
    if (value) {
      this.setAttribute('color', value);
    } else {
      this.removeAttribute('color');
    }
  }

  get label(): string | null {
    return this.getAttribute('label');
  }

  set label(value: string | null) {
    if (value == null) {
      this.removeAttribute('label');
    } else {
      this.setAttribute('label', value);
    }
  }

  get surfaceColor(): string | null {
    return this.getAttribute('surface-color');
  }

  set surfaceColor(value: string | null) {
    if (value == null) {
      this.removeAttribute('surface-color');
    } else {
      this.setAttribute('surface-color', value);
    }
  }

  get borderColor(): string | null {
    return this.getAttribute('border-color');
  }

  set borderColor(value: string | null) {
    if (value == null) {
      this.removeAttribute('border-color');
    } else {
      this.setAttribute('border-color', value);
    }
  }

  get textColor(): string | null {
    return this.getAttribute('text-color');
  }

  set textColor(value: string | null) {
    if (value == null) {
      this.removeAttribute('text-color');
    } else {
      this.setAttribute('text-color', value);
    }
  }

  get accentColor(): string | null {
    return this.getAttribute('accent-color');
  }

  set accentColor(value: string | null) {
    if (value == null) {
      this.removeAttribute('accent-color');
    } else {
      this.setAttribute('accent-color', value);
    }
  }

  get size(): ButtonSize {
    return (this.buttonEl.dataset.size as ButtonSize) ?? DEFAULT_BUTTON_SIZE;
  }

  set size(value: ButtonSize) {
    this.setAttribute('size', value);
  }

  get disabled(): boolean {
    return this.buttonEl.disabled;
  }

  set disabled(value: boolean) {
    this.toggleAttribute('disabled', value);
    this.syncDisabled();
  }

  get fullWidth(): boolean {
    return this.hasAttribute('full-width');
  }

  set fullWidth(value: boolean) {
    this.toggleAttribute('full-width', value);
    this.syncFullWidth();
  }

  get type(): string {
    return this.buttonEl.type;
  }

  set type(value: string) {
    this.setAttribute('type', value);
  }

  get iconOnly(): boolean {
    return this.hasAttribute('icon-only');
  }

  set iconOnly(value: boolean) {
    this.toggleAttribute('icon-only', value);
    this.syncIconOnly();
    this.syncHasLabel();
  }

  get dropdown(): boolean {
    return this.hasAttribute('dropdown');
  }

  set dropdown(value: boolean) {
    this.toggleAttribute('dropdown', value);
    this.syncDropdown();
  }

  get loading(): boolean {
    return this.hasAttribute('loading');
  }

  set loading(value: boolean) {
    this.toggleAttribute('loading', value);
    this.syncLoading();
  }

  get hasLabel(): boolean {
    const attr = this.getAttribute('has-label');
    if (attr !== null) {
      return attr !== 'false';
    }

    return !this.iconOnly && (this.hasLabelSlotContent() || Boolean(this.label && this.label.trim().length > 0));
  }

  set hasLabel(value: boolean) {
    this.setAttribute('has-label', value ? 'true' : 'false');
    this.syncHasLabel();
  }

  private syncAll = (): void => {
    this.syncVariant();
    this.syncColors();
    this.syncSize();
    this.syncDisabled();
    this.syncFullWidth();
    this.syncType();
    this.syncSlots();
    this.syncIconOnly();
    this.syncDropdown();
    this.syncLoading();
    this.syncHasLabel();
    this.syncAriaAttributes();
  };

  private syncVariant(): void {
    const variantAttr = this.getAttribute('variant');
    const variant: ButtonVariant = variantAttr && BUTTON_VARIANTS.includes(variantAttr as ButtonVariant)
      ? (variantAttr as ButtonVariant)
      : DEFAULT_BUTTON_VARIANT;

    this.buttonEl.dataset.variant = variant;
  }

  private syncColors(): void {
    // Reset our managed CSS variables each time so palette changes, direct overrides,
    // and removals behave predictably.
    for (const key of TONE_STYLE_VARS) {
      this.buttonEl.style.removeProperty(key);
    }
    for (const key of DIRECT_STYLE_VARS) {
      this.buttonEl.style.removeProperty(key);
    }

    const variant = this.variant;
    const color = this.color;

    const palette = color
      ? createButtonColorOverrides(variant, color)
      : null;

    if (palette) {
      for (const key of TONE_STYLE_VARS) {
        const value = palette[key];
        if (value) {
          this.buttonEl.style.setProperty(key, value);
        }
      }
    }

    const direct: Record<DirectStyleKey, string | null> = {
      '--fivra-button-surface': resolveColorValue(this.surfaceColor),
      '--fivra-button-border': resolveColorValue(this.borderColor),
      '--fivra-button-text': resolveColorValue(this.textColor),
      '--fivra-button-accent': resolveColorValue(this.accentColor),
    };

    for (const key of DIRECT_STYLE_VARS) {
      const value = direct[key];
      if (value) {
        this.buttonEl.style.setProperty(key, value);
      }
    }
  }

  private syncSize(): void {
    const sizeAttr = this.getAttribute('size');
    const size: ButtonSize = sizeAttr && BUTTON_SIZES.includes(sizeAttr as ButtonSize)
      ? (sizeAttr as ButtonSize)
      : DEFAULT_BUTTON_SIZE;

    this.buttonEl.dataset.size = size;
  }

  private syncDisabled(): void {
    const isDisabled = this.hasAttribute('disabled');
    this.buttonEl.disabled = isDisabled;
    if (isDisabled) {
      this.buttonEl.setAttribute('aria-disabled', 'true');
    } else {
      this.buttonEl.removeAttribute('aria-disabled');
    }
  }

  private syncFullWidth(): void {
    const fullWidth = this.hasAttribute('full-width');
    this.toggleAttribute('full-width', fullWidth);
    if (fullWidth) {
      this.buttonEl.dataset.fullWidth = 'true';
    } else {
      delete this.buttonEl.dataset.fullWidth;
    }
  }

  private syncType(): void {
    const typeAttr = this.getAttribute('type');
    this.buttonEl.type = typeAttr === 'submit' || typeAttr === 'reset' ? typeAttr : 'button';
  }

  private syncSlots = (): void => {
    const hasLeading = this.updateWrapper(this.leadingSlot, this.leadingWrapper);
    const hasTrailing = this.updateWrapper(this.trailingSlot, this.trailingWrapper);
    const hasLabel = this.updateLabel();

    this.buttonEl.dataset.leadingIcon = hasLeading ? 'true' : 'false';
    this.buttonEl.dataset.trailingIcon = hasTrailing ? 'true' : 'false';
    this.buttonEl.dataset.slotLabel = hasLabel ? 'true' : 'false';
  };

  private syncIconOnly(): void {
    if (this.iconOnly) {
      this.buttonEl.dataset.iconOnly = 'true';
    } else {
      delete this.buttonEl.dataset.iconOnly;
    }
  }

  private syncDropdown(): void {
    if (this.dropdown) {
      this.buttonEl.dataset.dropdown = 'true';
    } else {
      delete this.buttonEl.dataset.dropdown;
    }
  }

  private syncLoading(): void {
    if (this.loading) {
      this.buttonEl.dataset.loading = 'true';
      this.buttonEl.setAttribute('aria-busy', 'true');
    } else {
      delete this.buttonEl.dataset.loading;
      this.buttonEl.removeAttribute('aria-busy');
    }
  }

  private syncHasLabel(): void {
    const attr = this.getAttribute('has-label');
    const iconOnly = this.buttonEl.dataset.iconOnly === 'true';
    let hasLabel: boolean;

    if (attr !== null) {
      hasLabel = attr !== 'false';
    } else {
      hasLabel =
        !iconOnly &&
        (this.buttonEl.dataset.slotLabel === 'true' ||
          Boolean(this.label && this.label.trim().length > 0));
    }

    this.buttonEl.dataset.hasLabel = hasLabel ? 'true' : 'false';
  }

  private syncAriaAttributes(): void {
    const ariaLabel = this.getAttribute('aria-label');
    const ariaLabelledBy = this.getAttribute('aria-labelledby');
    const ariaHasPopup = this.getAttribute('aria-haspopup');
    const ariaExpanded = this.getAttribute('aria-expanded');

    if (ariaLabel !== null) {
      this.buttonEl.setAttribute('aria-label', ariaLabel);
    } else {
      this.buttonEl.removeAttribute('aria-label');
    }

    if (ariaLabelledBy !== null) {
      this.buttonEl.setAttribute('aria-labelledby', ariaLabelledBy);
    } else {
      this.buttonEl.removeAttribute('aria-labelledby');
    }

    if (ariaHasPopup !== null) {
      this.buttonEl.setAttribute('aria-haspopup', ariaHasPopup);
    } else if (this.dropdown) {
      this.buttonEl.setAttribute('aria-haspopup', 'menu');
    } else {
      this.buttonEl.removeAttribute('aria-haspopup');
    }

    if (ariaExpanded !== null) {
      this.buttonEl.setAttribute('aria-expanded', ariaExpanded);
    } else {
      this.buttonEl.removeAttribute('aria-expanded');
    }
  }

  private updateWrapper(slot: HTMLSlotElement, wrapper: HTMLElement): boolean {
    const hasContent = this.hasAssignedNodes(slot);
    wrapper.dataset.empty = hasContent ? 'false' : 'true';
    return hasContent;
  }

  private updateLabel(): boolean {
    const hasContent = this.hasLabelSlotContent();
    const label = this.label;
    const resolvedLabel = !hasContent && label && label.trim().length > 0 ? label : '';
    this.labelTextEl.textContent = resolvedLabel;
    const hasLabel = hasContent || resolvedLabel.length > 0;
    this.labelWrapper.dataset.empty = hasLabel ? 'false' : 'true';
    return hasLabel;
  }

  private hasAssignedNodes(slot: HTMLSlotElement): boolean {
    return slot
      .assignedNodes()
      .some((node) => node.nodeType === Node.ELEMENT_NODE || (node.textContent ?? '').trim().length > 0);
  }

  private hasLabelSlotContent(): boolean {
    return this.hasAssignedNodes(this.labelSlot);
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'fivra-button': FivraButtonElement;
  }
}

export function defineFivraButton(): void {
  if (typeof window === 'undefined' || window.customElements.get('fivra-button')) {
    return;
  }

  window.customElements.define('fivra-button', FivraButtonElement);
}
